export enum ShowsTypes {
  FETCH_SHOWS_REQUEST = 'FETCH_SHOWS_REQUEST',
  FETCH_SHOWS_SUCCESS = 'FETCH_SHOWS_SUCCESS',
  FETCH_SHOWS_FAILURE = 'FETCH_SHOWS_FAILURE',
  SELECT_SHOW = 'SELECT_SHOW',
  DESELECT_SHOW = 'DESELECT_SHOW',
}
